# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#

# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: reviung41
    artifact-name: reviung41lp
    cmake-args: '-DDTC_OVERLAY_FILE="${GITHUB_WORKSPACE}/config/reviung41lp.overlay:${GITHUB_WORKSPACE}/config/reviung41.keymap"'
  - board: nice_nano_v2
    shield: corne_left
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne_right
  - board: nice_nano_v2
    shield: settings_reset